# Generated by Django 4.1.3 on 2022-11-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='firmEmail',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userEmail',
        ),
    ]
