# Generated by Django 4.1.3 on 2022-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_firm_firmemail_remove_userinfo_useremail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name_plural': 'firms'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'userInfos'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE'), ('O', 'OTHER'), ('NM', 'NOTMENTIONED')], max_length=2, null=True),
        ),
    ]
